name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: refund-tracker-pro-android
        path: build/app/outputs/flutter-apk/app-release.apk

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build Windows
      run: flutter build windows --release
    
    - name: Create UWP Package
      run: |
        # Create APPX package for Windows Store
        flutter build windows --release
        cd build/windows/runner/Release
        # Package the app for UWP distribution
        powershell -Command "Compress-Archive -Path * -DestinationPath refund-tracker-pro-windows.zip"
    
    - name: Upload Windows Package
      uses: actions/upload-artifact@v4
      with:
        name: refund-tracker-pro-windows
        path: build/windows/runner/Release/refund-tracker-pro-windows.zip

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libblkid-dev liblzma-dev
        flutter pub get
    
    - name: Build Linux
      run: flutter build linux --release
    
    - name: Create AppImage
      run: |
        # Download AppImage tool
        wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
        chmod +x appimagetool-x86_64.AppImage
        
        # Create AppImage
        ./appimagetool-x86_64.AppImage build/linux/x64/release/bundle refund-tracker-pro-linux.AppImage
    
    - name: Upload Linux AppImage
      uses: actions/upload-artifact@v4
      with:
        name: refund-tracker-pro-linux
        path: refund-tracker-pro-linux.AppImage

  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build iOS
      run: flutter build ios --release --no-codesign
    
    - name: Upload iOS
      uses: actions/upload-artifact@v4
      with:
        name: refund-tracker-pro-ios
        path: build/ios/iphoneos/Runner.app
