name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: refund-tracker-pro-android
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Windows
        run: flutter build windows --release
      
      - name: Create Windows Installer
        run: |
          # Install WiX Toolset
          choco install wixtoolset -y
          
          # Create MSI installer
          cd build/windows/runner/Release
          candle -ext WixUIExtension -ext WixUtilExtension -dProductName="Refund Tracker Pro" -dProductVersion="1.0.0" -dManufacturer="Amino148" -dProductCode="{12345678-1234-1234-1234-123456789012}" -dUpgradeCode="{87654321-4321-4321-4321-210987654321}" -dInstallDir="[ProgramFilesFolder]\RefundTrackerPro" -dSourceDir="." -out "RefundTrackerPro.wixobj" "RefundTrackerPro.wxs"
          light -ext WixUIExtension -ext WixUtilExtension -out "RefundTrackerPro.msi" "RefundTrackerPro.wixobj"
      
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: refund-tracker-pro-windows
          path: |
            build/windows/runner/Release/
            build/windows/runner/Release/RefundTrackerPro.msi

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang libgtk-3-dev
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build Linux
        run: flutter build linux --release
      
      - name: Create AppImage
        run: |
          # Install AppImage tools
          wget -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool-x86_64.AppImage
          
          # Create AppImage
          ./appimagetool-x86_64.AppImage build/linux/x64/release/bundle/ RefundTrackerPro-x86_64.AppImage
      
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: refund-tracker-pro-linux
          path: |
            build/linux/x64/release/bundle/
            RefundTrackerPro-x86_64.AppImage

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      
      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: refund-tracker-pro-ios
          path: build/ios/iphoneos/

  create-release:
    needs: [build-android, build-windows, build-linux, build-ios]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            refund-tracker-pro-android/app-release.apk
            refund-tracker-pro-windows/RefundTrackerPro.msi
            refund-tracker-pro-linux/RefundTrackerPro-x86_64.AppImage
          body: |
            ## Refund Tracker Pro v${{ github.event.release.tag_name }}
            
            ### Downloads
            - **Android**: APK file for Android devices
            - **Windows**: MSI installer for Windows
            - **Linux**: AppImage for Linux distributions
            - **iOS**: Build files for iOS (requires Xcode for installation)
            
            ### Features
            - Multi-platform refund tracking
            - Local data storage
            - Notification system
            - Export functionality
            
            ### Installation
            - **Android**: Install the APK file directly
            - **Windows**: Run the MSI installer
            - **Linux**: Make the AppImage executable and run it
          draft: false
          prerelease: false
